ddata<-as.data.frame(expecteddeath)
liverd<-as.data.frame(liverpool)
ddata$week<-as.factor(ddata$week)
ddata$agegroup<-as.factor(ddata$agegroup)
ddata$sex<-as.factor(ddata$sex)
dglm1<-lm(log(death)~log(population)+week+agegroup*sex, data = ddata)
liverd$week<-as.factor(liverd$week)
liverpoolr<-predict.lm(dglm1,liverd,type="response")
ed<-exp(liverpoolr)
manchesterd<-as.data.frame(manchester)
manchesterd$week<-as.factor(manchesterd$week)
manchesterr<-predict.lm(dglm1,manchesterd,type="response")
output2<-as.data.frame(manchesterr)